apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-configuration-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-configuration-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Release.Namespace }}
