apiVersion: grafana.extension.oam.dev/v1alpha1
kind: DatasourceRegistration
metadata:
  name: poc
  namespace: observability
spec:
  grafana:
    service: grafana
    namespace: observability
    credentialSecret: grafana
    credentialSecretNamespace: observability
  datasource:
    name: loki-poc
    service: loki
    namespace: observability
    type: loki
    access: proxy
