apiVersion: grafana.extension.oam.dev/v1alpha1
kind: DatasourceRegistrationDeprecated
metadata:
  name: datasourceregistration-sample
spec:
  grafanaUrl: "http://grafana.c4c85a750c53a44a38b3902978f85d8e7.cn-hongkong.alicontainer.com"
  credentialSecret: grafana
  credentialSecretNamespace: grafana
  name: loki
  url: "http://loki.c4c85a750c53a44a38b3902978f85d8e7.cn-hongkong.alicontainer.com"
  type: loki
  access: proxy
